/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StreckenRouteImport } from './routes/strecken'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ReservierungenRouteImport } from './routes/reservierungen'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StreckenSlugRouteImport } from './routes/strecken.$slug'
import { Route as ReservierungTokenRouteImport } from './routes/reservierung.$token'

const StreckenRoute = StreckenRouteImport.update({
  id: '/strecken',
  path: '/strecken',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservierungenRoute = ReservierungenRouteImport.update({
  id: '/reservierungen',
  path: '/reservierungen',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StreckenSlugRoute = StreckenSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => StreckenRoute,
} as any)
const ReservierungTokenRoute = ReservierungTokenRouteImport.update({
  id: '/reservierung/$token',
  path: '/reservierung/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/reservierungen': typeof ReservierungenRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/strecken': typeof StreckenRouteWithChildren
  '/reservierung/$token': typeof ReservierungTokenRoute
  '/strecken/$slug': typeof StreckenSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/reservierungen': typeof ReservierungenRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/strecken': typeof StreckenRouteWithChildren
  '/reservierung/$token': typeof ReservierungTokenRoute
  '/strecken/$slug': typeof StreckenSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/reservierungen': typeof ReservierungenRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/strecken': typeof StreckenRouteWithChildren
  '/reservierung/$token': typeof ReservierungTokenRoute
  '/strecken/$slug': typeof StreckenSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/datenschutz'
    | '/impressum'
    | '/reservierungen'
    | '/services'
    | '/sitemap.xml'
    | '/strecken'
    | '/reservierung/$token'
    | '/strecken/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/datenschutz'
    | '/impressum'
    | '/reservierungen'
    | '/services'
    | '/sitemap.xml'
    | '/strecken'
    | '/reservierung/$token'
    | '/strecken/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/datenschutz'
    | '/impressum'
    | '/reservierungen'
    | '/services'
    | '/sitemap.xml'
    | '/strecken'
    | '/reservierung/$token'
    | '/strecken/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DatenschutzRoute: typeof DatenschutzRoute
  ImpressumRoute: typeof ImpressumRoute
  ReservierungenRoute: typeof ReservierungenRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StreckenRoute: typeof StreckenRouteWithChildren
  ReservierungTokenRoute: typeof ReservierungTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/strecken': {
      id: '/strecken'
      path: '/strecken'
      fullPath: '/strecken'
      preLoaderRoute: typeof StreckenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservierungen': {
      id: '/reservierungen'
      path: '/reservierungen'
      fullPath: '/reservierungen'
      preLoaderRoute: typeof ReservierungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strecken/$slug': {
      id: '/strecken/$slug'
      path: '/$slug'
      fullPath: '/strecken/$slug'
      preLoaderRoute: typeof StreckenSlugRouteImport
      parentRoute: typeof StreckenRoute
    }
    '/reservierung/$token': {
      id: '/reservierung/$token'
      path: '/reservierung/$token'
      fullPath: '/reservierung/$token'
      preLoaderRoute: typeof ReservierungTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface StreckenRouteChildren {
  StreckenSlugRoute: typeof StreckenSlugRoute
}

const StreckenRouteChildren: StreckenRouteChildren = {
  StreckenSlugRoute: StreckenSlugRoute,
}

const StreckenRouteWithChildren = StreckenRoute._addFileChildren(
  StreckenRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DatenschutzRoute: DatenschutzRoute,
  ImpressumRoute: ImpressumRoute,
  ReservierungenRoute: ReservierungenRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StreckenRoute: StreckenRouteWithChildren,
  ReservierungTokenRoute: ReservierungTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
